language: java

env:
  global:
     - GH_REF: github.com/hscells/CSC241.git
     - secure: XXqxidH/NKflladdsfKNyqRhNe0fUm6zz6bxMnmEnjFo3RJIXFI4r0vLMQLRQEWnF+Aj1zmn283RN72/0MlmfZ0EsJbocVAi6D6XAUFU3Tm1eQyRNLnf+8bo0otwn5OamDLmRz/KmIVvtEC1ouo/Q1wJReUur6SzQQitO/M1zdk=

before_script:
 - cd Homework\ 4/
 - javac *.java
 - cd ../
 - git config --global user.email "harryscells@gmail.com"
 - git config --global user.name "hscells"
 - git config --global push.default matching

after_script:
 - git clone https://github.com/hscells/hscells.github.io.git
 - javadoc Homework\ 4/Main.java -d hscells.github.io/CSC241/doc
 - cd hscells.github.io
 - git add *
 - git commit -m "updated CSC241 javadoc"
 - git push --force --quiet "https://${secure}@${GH_REF}" master:gh-pages > /dev/null 2>&1
